name: Build toolbox
on: [push]
jobs:
  build:
    name: Build toolbox
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.15.0
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run build
        uses: matlab-actions/run-build@v2
