name: Build toolbox
on: [push]
jobs:
  build:
    name: Build toolbox
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            .buildtool
            build
          key: ${{ runner.os }}-build-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref_name }}
            ${{ runner.os }}-build-main
            ${{ runner.os }}-build-
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run build
        uses: matlab-actions/run-build@v2
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Blink Toolbox
          path: build/blink.mltbx
