name: Build toolbox
on: [push]
jobs:
  build:
    name: Build toolbox
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install compiler dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-11 gcc-11-base gcc-11-doc g++-11
          sudo apt-get install libstdc++-11-dev libstdc++-11-doc
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run build
        uses: matlab-actions/run-build@v2
