name: Build toolbox
on: [push]
jobs:
  build:
    name: Build toolbox
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - uses: bazel-contrib/setup-bazel@0.19.0
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          cache: true
      - name: Run build
        uses: matlab-actions/run-build@v3
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: Blink Toolbox
          path: release/Blink.mltbx
