name: Build toolbox
on: [push]
jobs:
  build:
    name: Build toolbox
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install required compilers
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
        shell: bash
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run build
        uses: matlab-actions/run-build@v2
        env:
         CC:   gcc-10
         CXX:  g++-10
